[platformio]
core_dir = ../Tag_FW_nRF52811/tag_fw/core

[env:Newton_M3_Photo_Viewer]
platform = nordicnrf52@9.6.0
board = nrf52811_dk
framework = arduino
board_build.ldscript = photo_viewer.ld
build_flags =
    -Os
    -ffunction-sections
    -fdata-sections
    -Wl,--gc-sections
    -Tphoto_viewer.ld
